name: ANGLE

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "arm" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-latest

    steps:
      - name: Get ANGLE
        uses: actions/checkout@v4
        with:
          path: 'angle'

      - name: Build ANGLE
        shell: bash
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=`pwd`/depot_tools:$PATH
          echo $PATH
          cd angle
          python scripts/bootstrap.py
          gclient sync
          gn gen out/Android-${{matrix.arch}}
          autoninja -C out/Android-${{matrix.arch}} angle_apks
      - name: Upload ANGLE
        uses: actions/upload-artifact@v4
        with:
          name: angle-libs-${{matrix.arch}}
          path: |
            angle/out/Android-${{matrix.arch}}/apks/*.apk

